### PR TITLE
Improve readability of the run function

### PR DESCRIPTION
**Pull request by RickvdStaaij**
### What

I saw some scrutinizer comments I wanted to fix, hopefully increasing the grade of the code :)

### CODE REVIEW

**Comment by RickvdStaaij** [comment]
Missing parameter comment, really PHP5?

**Comment by RickvdStaaij** [comment]
I give up

**Comment by RickvdStaaij** [comment]
@eXistenZNL open source should be fun :cry:

**Comment by eXistenZNL** [comment]
@RickvdStaaij care to give this another try?

**Pull request merged**
